---
- name: Set up a new MacBook for development
  hosts: localhost
  tasks:
    - name: Check if Homebrew is installed
      command: brew --version
      register: brew_check
      ignore_errors: yes

    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: brew_check.rc != 0

    - name: Ensure Homebrew is up-to-date
      command: brew update
      when: brew_check.rc == 0

    - name: Check if Homebrew packages are installed
      command: brew list --formula
      register: installed_brew_packages

    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - node
        - python
        - docker
        - wget
        - nvm
      when: "'{{ item }}' not in installed_brew_packages.stdout"

    - name: Check if Homebrew Cask applications are installed
      command: brew list --cask
      register: installed_cask_apps

    - name: Install Homebrew Cask applications
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - visual-studio-code
        - google-chrome
        - vlc
        - protonvpn
        - brave-browser
        - postman
      when: "'{{ item }}' not in installed_cask_apps.stdout"
